### ISSUE TITLE
Mixed up shared_credential_files with shared_config_files

### ISSUE THREAD

**Issue by chuck-alt-delete** [MaterializeInc/terraform-aws-kafka-privatelink#3]
## Problem

Reference:
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs#shared-configuration-and-credentials-files

Right now we have this: https://github.com/MaterializeInc/terraform-aws-kafka-privatelink/blob/main/providers.tf#L12:

```hcl
provider "aws" {
  region                   = var.aws_region
  shared_credentials_files = var.aws_config_file
  profile                  = var.aws_profile
}
```

But `var.aws_config_file` defaults to `["~/.aws/config"]`, which is a config file, not a credential file.

## Suggestion

The AWS provider already has sensible defaults for environment variables and AWS config / credential locations. I suggest we remove those from `variables.tf` entirely and keep only the region. If users want further customization, they can use environment variables.

If we do want to keep what's in variables.tf, let's change `aws_config_file` to `aws_credentials_file` and set the default to `["~/.aws/credentials"]`. Or I suppose it might be easier to change `shared_credentials_files` to `shared_config_files` in providers.tf.

**Comment by blak3mill3r** [comment]
This fixed the issue for me
